import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Profile | QurbaniHat",
  description: "Generated by create next app",
};
const MyProfilePage = async () => {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  const user = session?.user;

  return (
    <div className="container mx-auto px-4 py-10 min-h-[80vh] flex justify-center items-center">
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 w-full max-w-md">

        {/* Avatar */}
        <div className="flex flex-col items-center mb-6">
          <div className="w-24 h-24 rounded-full ring-4 ring-green-800 ring-offset-2 overflow-hidden mb-4">
            {user?.image && user.image.startsWith("http") ? (
              <Image
                src={user.image}
                alt={user.name}
                width={96}
                height={96}
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="w-24 h-24 bg-green-800 text-white flex items-center justify-center text-3xl font-bold">
                {user?.name?.charAt(0).toUpperCase()}
              </div>
            )}
          </div>
          <h2 className="text-2xl font-bold text-gray-800">{user?.name}</h2>
          <p className="text-gray-400 text-sm mt-1">{user?.email}</p>
        </div>

        {/* Info */}
        <div className="space-y-3 mb-6">
          <div className="bg-gray-50 rounded-xl px-4 py-3">
            <p className="text-xs text-gray-400">Name</p>
            <p className="text-sm font-semibold text-gray-700">{user?.name}</p>
          </div>
          <div className="bg-gray-50 rounded-xl px-4 py-3">
            <p className="text-xs text-gray-400">Email</p>
            <p className="text-sm font-semibold text-gray-700">{user?.email}</p>
          </div>
        </div>

        {/* Update Button */}
        <Link
          href="/my_profile/update_info"
          className="block w-full text-center py-3 bg-green-800 text-white font-medium rounded-xl hover:bg-green-900 transition-colors duration-200"
        >
          Update Information
        </Link>

      </div>
    </div>
  );
};

export default MyProfilePage;