import { Playfair_Display, Montserrat} from "next/font/google";
import "./globals.css";


const montserrat =  Montserrat({
  variable: "--font-montserrat",
   subsets: ["latin"],
 
})
export const playFair_Display = Playfair_Display({
  variable: "--font-playfair-display",
   subsets: ["latin"],
 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.className}  h-full antialiased`}
      data-theme="light"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
