import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);

import {  Montserrat} from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";



const montserrat =  Montserrat({
  variable: "--font-montserrat",
   subsets: ["latin"],
 
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.className}  h-full antialiased`}
      data-theme="light"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
       
        
          {children}
         <ToastContainer position="top-right" autoClose={3000} />
         
       
        </body>
    </html>
  );
}
